### ISSUE TITLE
OrthographicCameraBundle does not render

### ISSUE THREAD

**Issue by RossLote** [ForesightMiningSoftwareCorporation/bevy_polyline#29]
When rendering using `OrthographicCameraBundle` nothing renders to the screen. From what I can tell, this used to work. Maybe an issue specific to a newer version of bevy.

**Comment by Meisterlama** [comment]
I've been playing with some settings and I was able to get the line rendering with an Orthographic camera by creating a Camera3dBundle (Like in the examples) and setting the projection to Orthographic manually.

My bevy's newbie guess would be that those bundle don't have the same archetype. 3dBundle uses a generic `Projection` which is a enum wrapping Perspective and Orthographic, whereas 2dBundle apparently directly uses an `OrthographicProjection`.

**Comment by aevyrie** [comment]
I am also using the ortho camera in 3d like the bevy examples, without issue.
