### ISSUE TITLE
Lines with perspective disappear at certain camera angles

### ISSUE THREAD

**Issue by NEO97online** [ForesightMiningSoftwareCorporation/bevy_polyline#46]
With `perspective: true`, moving the camera close to lines or in certain angles makes them disappear. I'm not exactly sure if they're being culled or if something else is going on:

https://user-images.githubusercontent.com/28285686/236361731-cca3a06a-1508-4f9d-bcd8-947cd4ce96c0.mp4

(Don't mind the strangely uncropped window)

**Comment by NEO97code** [comment]
`NoFrustumCulling` on the entity with the PolylineBundle didn't have any effect, unfortunately

**Comment by aevyrie** [comment]
Hm... I have a hunch that what's happening is the vertex that goes offscreen is turning into a NaN. I haven't seen this before because usually I don't have long two-vertex segments, instead they are subdivided into much more dense polylines so this issue is not visible.

**Comment by NEO97code** [comment]
Seems like it might be something like that. It definitely seems to be happening when either of the two points goes outside the camera's frustum.

Interestingly, when HDR is enabled, the lines don't disappear but take on a blueish or negative appearance. Maybe this is a clue:



https://user-images.githubusercontent.com/28285686/236978688-850641b4-08bb-4d2d-832c-e25008417195.mp4

**Comment by aevyrie** [comment]
Well this is spooky, thanks for providing more details. Could you try adding a bunch of subdivisions to your lines to see if that functions as a workaround?

Oddly enough I was using the bevy 0.9 version of this today and had a similar case of a two-vertex line, but was unable to replicate this.

**Comment by NEO97code** [comment]
Adding more line segments doesn't resolve the issue, but rather than the entire line turning translucent blue, it's split at the subdivisions like this (sorry for the pause menu overlay, but you can still see the issue):

![image](https://github.com/ForesightMiningSoftwareCorporation/bevy_polyline/assets/28285686/54269ed7-5228-4dd8-be79-4157f63e0e40)

**Comment by aevyrie** [comment]
@IceSentry any idea what could be causing this? You did the 0.10 migration, and you might have some insight into other bevy changes that may be causing this.

**Comment by IceSentry** [comment]
Fixed in #47
